// Multi-language snippet library, length-tagged.
const SNIPPET_LIBRARIES = {
  java: {
    short: [
      'int i = 0;',
      'return n;',
      'arr[i] = 1;',
      'String s = "";',
      'count++;',
      'list.add(x);',
      'boolean ok;',
      'if (n > 0) {}',
      'x = y * 2;',
      'break;',
      'continue;',
      'this.x = x;',
    ],
    medium: [
      'String name = "Alice";',
      'int sum = a + b + c;',
      'while (i < n) i++;',
      'public void run() { }',
      'list.add(new Node(x));',
      'if (x > 0) return x * 2;',
      'for (int x : nums) sum += x;',
      'return Math.max(a, b);',
      'Set<Integer> seen = new HashSet<>();',
      'static final int MAX = 100;',
      'try { task.run(); } catch (Exception e) {}',
    ],
    long: [
      'for (int i = 0; i < arr.length; i++) {',
      'public static void main(String[] args) {',
      'System.out.println("Hello, World!");',
      'private final Map<String, Integer> cache = new HashMap<>();',
      'if (s == null || s.isEmpty()) return null;',
      'return list.stream().filter(x -> x > 0).count();',
      'public class Solution implements Runnable {',
      'List<String> result = new ArrayList<String>();',
      'public int compareTo(Node o) { return this.val - o.val; }',
      'throw new IllegalArgumentException("invalid input");',
    ],
  },
  python: {
    short: [
      'i = 0',
      'return n',
      'arr[i] = 1',
      's = ""',
      'count += 1',
      'lst.append(x)',
      'is_ok = True',
      'if n > 0:',
      'x = y * 2',
      'break',
      'continue',
      'self.x = x',
    ],
    medium: [
      'name = "Alice"',
      'total = a + b + c',
      'while i < n: i += 1',
      'def run(self): pass',
      'nums.append(Node(x))',
      'if x > 0: return x * 2',
      'total = sum(x for x in nums)',
      'return max(a, b)',
      'unique = set(items)',
      'MAX_VALUE = 100',
      'with open(path) as f: data = f.read()',
    ],
    long: [
      'for i in range(len(arr)):',
      'if __name__ == "__main__":',
      'print("Hello, World!")',
      'cache: dict[str, int] = {}',
      'if s is None or len(s) == 0: return None',
      'return [x for x in items if x > 0]',
      'class Solution: pass',
      'result = sorted(items, key=lambda x: x.value)',
      'def __init__(self, val=0, next=None):',
      'raise ValueError("invalid input")',
    ],
  },
  javascript: {
    short: [
      'let i = 0;',
      'return n;',
      'arr[i] = 1;',
      'let s = "";',
      'count++;',
      'list.push(x);',
      'let ok = true;',
      'if (n > 0) {}',
      'x = y * 2;',
      'break;',
      'continue;',
      'this.x = x;',
    ],
    medium: [
      'const name = "Alice";',
      'const sum = a + b + c;',
      'while (i < n) i++;',
      'function run() { }',
      'list.push(new Node(x));',
      'if (x > 0) return x * 2;',
      'for (const x of nums) sum += x;',
      'return Math.max(a, b);',
      'const seen = new Set();',
      'const MAX = 100;',
      'try { task(); } catch (e) {}',
    ],
    long: [
      'for (let i = 0; i < arr.length; i++) {',
      'document.addEventListener("click", () => {',
      'console.log("Hello, World!");',
      'const cache = new Map();',
      'if (s == null || s.length === 0) return null;',
      'return list.filter(x => x > 0).length;',
      'class Solution { constructor() {} }',
      'const result = items.sort((a, b) => a - b);',
      'async function fetchData(url) { return fetch(url); }',
      'throw new Error("invalid input");',
    ],
  },
  cpp: {
    short: [
      'int i = 0;',
      'return n;',
      'arr[i] = 1;',
      'count++;',
      'vec.push_back(x);',
      'bool ok;',
      'if (n > 0) {}',
      'x = y * 2;',
      'break;',
      'continue;',
      'delete ptr;',
      'this->x = x;',
    ],
    medium: [
      'string name = "Alice";',
      'int sum = a + b + c;',
      'while (i < n) i++;',
      'void run() { }',
      'vec.push_back(Node(x));',
      'if (x > 0) return x * 2;',
      'for (int x : nums) sum += x;',
      'return std::max(a, b);',
      'std::set<int> seen;',
      'static const int MAX = 100;',
      'try { run(); } catch (std::exception& e) {}',
    ],
    long: [
      'for (int i = 0; i < arr.size(); i++) {',
      'int main(int argc, char* argv[]) {',
      'std::cout << "Hello, World!" << std::endl;',
      'std::map<std::string, int> cache;',
      'if (s.empty()) return nullptr;',
      'std::vector<int> result(arr.size());',
      'class Solution { public: virtual void solve(); };',
      'auto it = std::find(v.begin(), v.end(), x);',
      'template<typename T> T add(T a, T b) { return a + b; }',
      'throw std::invalid_argument("invalid input");',
    ],
  },
  ruby: {
    short: [
      'i = 0',
      'return n',
      'arr[i] = 1',
      's = ""',
      'count += 1',
      'arr.push(x)',
      'ok = true',
      'if n > 0',
      'x = y * 2',
      'break',
      'next',
      'puts msg',
    ],
    medium: [
      'name = "Alice"',
      'total = a + b + c',
      'while i < n; i += 1; end',
      'def run; end',
      'arr.push(Node.new(x))',
      'return x * 2 if x > 0',
      'total = nums.sum',
      'result = [a, b].max',
      'unique = items.uniq',
      'MAX_VALUE = 100',
      'data = File.read(path)',
    ],
    long: [
      '(0...arr.length).each do |i|',
      'if __FILE__ == $0',
      'puts "Hello, World!"',
      'cache = Hash.new { |h, k| h[k] = [] }',
      'return nil if s.nil? || s.empty?',
      'items.select { |x| x > 0 }',
      'class Solution; def initialize; end; end',
      'result = items.sort_by { |x| x.value }',
      'def initialize(val = 0, next_node = nil)',
      'raise ArgumentError, "invalid input"',
    ],
  },
  go: {
    short: [
      'i := 0',
      'return n',
      'arr[i] = 1',
      's := ""',
      'count++',
      'slice = append(slice, x)',
      'ok := true',
      'if n > 0 {}',
      'x = y * 2',
      'break',
      'continue',
      'defer f.Close()',
    ],
    medium: [
      'name := "Alice"',
      'sum := a + b + c',
      'for i < n { i++ }',
      'func run() {}',
      'nodes = append(nodes, Node{x})',
      'if x > 0 { return x * 2 }',
      'for _, x := range nums { sum += x }',
      'return math.Max(a, b)',
      'seen := make(map[int]bool)',
      'const MAX = 100',
      'data, err := os.ReadFile(path)',
    ],
    long: [
      'for i := 0; i < len(arr); i++ {',
      'func main() {',
      'fmt.Println("Hello, World!")',
      'cache := make(map[string]int)',
      'if s == "" { return nil }',
      'result := filter(items, func(x int) bool { return x > 0 })',
      'type Solution struct { vals []int }',
      'sort.Slice(items, func(i, j int) bool { return items[i] < items[j] })',
      'func NewNode(val int, next *Node) *Node { return &Node{val, next} }',
      'return errors.New("invalid input")',
    ],
  },
};

const LANGUAGES = ['java', 'python', 'javascript', 'cpp', 'ruby', 'go'];
const LANG_DISPLAY = {
  java: 'JAVA',
  python: 'PYTHON',
  javascript: 'JS',
  cpp: 'C++',
  ruby: 'RUBY',
  go: 'GO',
};

function pickSnippet(actionKind, lang) {
  let bucket;
  if (actionKind === 'dribble' || actionKind === 'position') bucket = 'short';
  else if (actionKind === 'shoot' || actionKind === 'block') bucket = 'long';
  else bucket = 'medium';

  const language = (lang && SNIPPET_LIBRARIES[lang])
    ? lang
    : LANGUAGES[Math.floor(Math.random() * LANGUAGES.length)];
  const pool = SNIPPET_LIBRARIES[language][bucket];
  const text = pool[Math.floor(Math.random() * pool.length)];
  return { text, lang: language };
}

function timeLimitFor(actionKind) {
  if (actionKind === 'dribble' || actionKind === 'position') return 6;
  if (actionKind === 'shoot') return 15;
  if (actionKind === 'block') return 12;
  return 10;
}
